=== bibsys/DSpace/dspace/config/submission-forms.dtd
<!-- DSpace Custom Submit input form definition language -->


 <!ELEMENT input-forms (form-definitions, form-value-pairs) >

 <!ELEMENT form-definitions (form)+ >
 <!ELEMENT form (row)+ >
 <!ELEMENT row (field|relation-field)+ >
 <!ATTLIST form name NMTOKEN #REQUIRED>

 <!ELEMENT field (dc-schema, dc-element, dc-qualifier?, language?, repeatable?, label, style?, type-bind?, input-type, hint, required?, regex?, vocabulary?, visibility?, readonly?, help?) >
 <!ELEMENT dc-schema (#PCDATA) >
 <!ELEMENT dc-element (#PCDATA) >
 <!ELEMENT dc-qualifier (#PCDATA) >
 <!ELEMENT language (#PCDATA)>
 <!ELEMENT type-bind (#PCDATA) >

 <!ELEMENT repeatable (#PCDATA) >
 <!ELEMENT label (#PCDATA) >
 <!ELEMENT style (#PCDATA) >
 <!ELEMENT input-type (#PCDATA)>

 <!ELEMENT hint (#PCDATA) >
 <!ELEMENT help (#PCDATA)>
 <!ELEMENT required (#PCDATA)>
 <!ELEMENT name-variants (#PCDATA)>
 <!ELEMENT regex (#PCDATA) >

 <!ELEMENT form-value-pairs (value-pairs)* >
 <!ELEMENT value-pairs (pair)+ >

 <!-- ***
        To assign a particular 'value-pairs' list to a particular dropdown 'input-type'
        field, as found on a particular form, put:
        - value-pairs/@value-pairs-name string into
           form/page/field/input-type/@value-pairs-name
        - form/page/field/@DCelement + '_' + form/field/DCqualifier into
           value-pairs/@dc-term
             (e.g. 'language_iso')
  -->
 <!ATTLIST value-pairs value-pairs-name CDATA #REQUIRED
                            dc-term   CDATA #REQUIRED
 >

 <!ELEMENT pair (displayed-value,stored-value) >
 <!ELEMENT displayed-value (#PCDATA)>
 <!ELEMENT stored-value (#PCDATA)>

 <!ATTLIST input-type value-pairs-name CDATA  #IMPLIED>

 <!ELEMENT vocabulary (#PCDATA) >

 <!ATTLIST vocabulary closed (true|false) "false">

 <!ELEMENT visibility (#PCDATA) >

 <!ATTLIST language value-pairs-name CDATA  #IMPLIED>

 <!ELEMENT readonly (#PCDATA) >

<!ELEMENT relationship-type (#PCDATA) >
<!ELEMENT search-configuration (#PCDATA) >
<!ELEMENT filter (#PCDATA) >
<!ELEMENT externalsources (#PCDATA) >
<!ELEMENT relation-field (relationship-type, search-configuration, filter?, repeatable?, name-variants?, label, type-bind?, hint, linked-metadata-field?, externalsources?, required?, regex?, visibility?)>
<!ELEMENT linked-metadata-field (dc-schema, dc-element, dc-qualifier?, input-type)>

=== bibsys/DSpace/dspace/config/submission-forms.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE input-forms SYSTEM "submission-forms.dtd">
<input-forms>
  <form-definitions>
    <!-- MASTER THESIS ==================================================== -->
    <form name="master-thesis-dc-contributor-author">
      <row>
        <field>
          <dc-schema>dc</dc-schema>
          <dc-element>contributor</dc-element>
          <dc-qualifier>author</dc-qualifier>
          <repeatable>false</repeatable>
          <label>Name</label>
          <input-type>onebox</input-type>
          <hint>Enter the name of the author in the form "Lastname, Firstname" [i.e. Smith, Josh]. If any suggestions have been found, click on it to fill the form</hint>
          <required>You must enter the author name</required>
        </field>
      </row>
      <row>
        <field>
          <dc-schema>authors</dc-schema>
          <dc-element>email</dc-element>
          <repeatable>false</repeatable>
          <label>Email</label>
          <input-type>onebox</input-type>
          <hint>Enter the email where to contact the author</hint>
          <required>You must enter a valid email address.</required>
        </field>
      </row>
      <row>
        <field>
          <dc-schema>authors</dc-schema>
          <dc-element>institution</dc-element>
          <dc-qualifier>name</dc-qualifier>
          <repeatable>false</repeatable>
          <label>Institution</label>
          <style>col-6</style>
          <input-type>onebox</input-type>
          <hint>Enter the author institution name</hint>
          <required>You must enter the author institution name</required>
        </field>
        <field>
          <dc-schema>authors</dc-schema>
          <dc-element>identifier</dc-element>
          <dc-qualifier>fgs</dc-qualifier>
          <repeatable>false</repeatable>
          <label>FGS</label>
          <style>col-6</style>
          <input-type>onebox</input-type>
          <hint>FGS Identifier</hint>
          <readonly>all</readonly>
        </field>
        <field>
          <dc-schema>authors</dc-schema>
          <dc-element>identifier</dc-element>
          <dc-qualifier>noma</dc-qualifier>
          <repeatable>false</repeatable>
          <label>NOMA</label>
          <input-type>hidden</input-type>
          <hint>NOMA Identifier</hint>
          <readonly>all</readonly>
        </field>
      </row>
      <row>
        <field>
          <dc-schema>masterthesis</dc-schema>
          <dc-element>degree</dc-element>
          <dc-qualifier>code</dc-qualifier>
          <repeatable>false</repeatable>
          <label>Degree</label>
          <input-type>degree_select</input-type>
          <hint>Select a degree</hint>
          <required>Select the degree related to the author.</required>
          <visibility>submission</visibility>
        </field>
        <field>
          <dc-schema>masterthesis</dc-schema>
          <dc-element>degree</dc-element>
          <dc-qualifier>code</dc-qualifier>
          <repeatable>false</repeatable>
          <label>Degree code</label>
          <input-type>onebox</input-type>
          <hint>Enter the degree code. Please be CAREFUL and consistent with degree label</hint>
          <required>Enter the degree code</required>
          <visibility>workflow</visibility>
        </field>
      </row>
      <row>
        <field>
          <dc-schema>masterthesis</dc-schema>
          <dc-element>degree</dc-element>
          <dc-qualifier>label</dc-qualifier>
          <repeatable>false</repeatable>
          <label>DegreeLabel</label>
          <input-type>hidden</input-type>
          <hint/>
          <visibility>submission</visibility>
        </field>
        <field>
          <dc-schema>masterthesis</dc-schema>
          <dc-element>degree</dc-element>
          <dc-qualifier>label</dc-qualifier>
          <repeatable>false</repeatable>
          <label>DegreeLabel</label>
          <input-type>onebox</input-type>
          <hint>Enter the degree label. Please be CAREFUL and consistent with degree code</hint>
          <required>Enter the degree label</required>
          <visibility>workflow</visibility>
        </field>
      </row>
    </form>
    <form name="master-thesis-dc-contributor-advisor">
      <row>
        <field>
          <dc-schema>dc</dc-schema>
          <dc-element>contributor</dc-element>
          <dc-qualifier>advisor</dc-qualifier>
          <repeatable>false</repeatable>
          <label>Name</label>
          <input-type>onebox</input-type>
          <hint>Enter the supervisor name of this item in the form "Lastname, Firstname" [i.e. Smith, Josh or Smith, J]</hint>
          <required>You must enter at least the supervisor</required>
        </field>
      </row>
      <row>
        <field>
          <dc-schema>advisors</dc-schema>
          <dc-element>email</dc-element>
          <repeatable>false</repeatable>
          <label>Email</label>
          <input-type>onebox</input-type>
          <hint>Enter the email where to contact the supervisor</hint>
          <required>You must enter a valid email address.</required>
        </field>
      </row>
      <row>
        <field>
          <dc-schema>advisors</dc-schema>
          <dc-element>institution</dc-element>
          <dc-qualifier>name</dc-qualifier>
          <repeatable>false</repeatable>
          <label>Institution</label>
          <input-type>onebox</input-type>
          <hint>Choose the supervisor institution affiliation</hint>
          <required>You must specify the institution name of the supervisor</required>
        </field>
      </row>
    </form>
    <form name="master-thesis">
      <row>
        <field>
          <dc-schema>dc</dc-schema>
          <dc-element>contributor</dc-element>
          <dc-qualifier>author</dc-qualifier>
          <repeatable>true</repeatable>
          <label>Author(s)</label>
          <input-type>group</input-type>
          <hint>Enter the names of the authors of this item.</hint>
          <required>At least one author is required</required>
        </field>
      </row>
      <row>
        <field>
          <dc-schema>dc</dc-schema>
          <dc-element>contributor</dc-element>
          <dc-qualifier>advisor</dc-qualifier>
          <repeatable>true</repeatable>
          <label>Supervisor(s)</label>
          <input-type>group</input-type>
          <hint>Enter each supervisor of the thesis.</hint>
          <required>At least one supervisor is required</required>
        </field>
      </row>
      <row>
        <field>
          <dc-schema>dc</dc-schema>
          <dc-element>title</dc-element>
          <repeatable>false</repeatable>
          <label>Title</label>
          <input-type>onebox</input-type>
          <hint>Enter the whole title and subtitle of the thesis. Use a colon between title and subtitle (unless title ends with a question mark).</hint>
          <required>You must enter a title.</required>
        </field>
      </row>
      <row>
        <field>
          <dc-schema>dc</dc-schema>
          <dc-element>description</dc-element>
          <dc-qualifier>abstract</dc-qualifier>
          <language value-pairs-name="common_iso_languages">true</language>
          <repeatable>true</repeatable>
          <label>Abstract</label>
          <input-type>textarea</input-type>
          <hint>Enter the abstract of the item. For additional abstract, use the below "add" link.</hint>
          <required>You must enter an abstract.</required>
        </field>
      </row>
      <row>
        <field>
          <dc-schema>dc</dc-schema>
          <dc-element>language</dc-element>
          <dc-qualifier>iso-639-2</dc-qualifier>
          <repeatable>false</repeatable>
          <label>Language</label>
          <input-type value-pairs-name="common_iso_languages_639_2">dropdown</input-type>
          <hint>Select the language of the main content of the thesis.</hint>
          <required>You must choose a language.</required>
        </field>
      </row>
      <row>
        <field>
          <dc-schema>dc</dc-schema>
          <dc-element>subject</dc-element>
          <repeatable>true</repeatable>
          <label>Subject Keywords</label>
          <input-type>tag</input-type>
          <hint>Use a comma between keywords.</hint>
        </field>
      </row>
      <row>
        <field>
          <dc-schema>masterthesis</dc-schema>
          <dc-element>session</dc-element>
          <repeatable>false</repeatable>
          <label>Session</label>
          <input-type value-pairs-name="masterthesis_session">dropdown</input-type>
          <hint>Confidential data: it will not be published.</hint>
          <required>You must choose a session period for this item.</required>
        </field>
        <field>
          <dc-schema>dc</dc-schema>
          <dc-element>date</dc-element>
          <dc-qualifier>issued</dc-qualifier>
          <repeatable>false</repeatable>
          <label>Year</label>
          <input-type>year</input-type>
          <hint/>
          <required>You must choose a year period for this item.</required>
        </field>
      </row>
    </form>
    <!-- MASTER THESIS - CATARETRO ======================================== -->
    <form name="master-thesis-cataretro-dc-contributor-author">
      <row>
        <field>
          <dc-schema>dc</dc-schema>
          <dc-element>contributor</dc-element>
          <dc-qualifier>author</dc-qualifier>
          <repeatable>false</repeatable>
          <label>Name</label>
          <input-type>onebox</input-type>
          <hint>
            Enter the names of the authors of this item in the form "Lastname, Firstname" [i.e. Smith, Josh or Smith, J].
          </hint>
          <required>You must enter at least the author.</required>
        </field>
      </row>
      <row>
        <field>
          <dc-schema>authors</dc-schema>
          <dc-element>institution</dc-element>
          <dc-qualifier>name</dc-qualifier>
